#!/bin/bash

export MAVEN_DEBUG_OPTS="-Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8000"
export MAVEN_OPTS="-Xms1024m -Xmx2048m -noverify -XX:MaxMetaspaceSize=760m"
export KUBE_EDITOR="nvim"

export platusers="duboisf,marcantoine-bibeau,lavoiedn,jagdeepgithub,Masterdo,alexgervais,joanroch"

open_pull_request() {
    if [ ! -z $1 ] && [ $1 == 'all' ]; then
        prusers="-r $platusers"
    else
        prusers=""
    fi
    hub pull-request --copy $prusers
}

alias openpr="open_pull_request"
alias vpnstart="sudo openconnect -b --authgroup=Duo --user=leo.almeida iceman.appdirect.com"
alias vpnstartbatman="sudo openconnect -b --authgroup=Duo --user=leo.almeida batman.appdirect.com"
alias vpnstop="sudo pkill -SIGINT openconnect"
alias buildad="mvn clean install -pl '!appdirect' -Dmaven.test.skip=true -DskipTests=true"

PATH="$HOME/dev/src/platform/platform-army-knife/kubernetes/kops:$PATH"
