#!/bin/bash

export MAVEN_DEBUG_OPTS="-Xdebug -Xnoagent -Djava.compiler=NONE -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8000"
export MAVEN_OPTS="-Xms1024m -Xmx2048m -noverify -XX:MaxMetaspaceSize=760m"
export KUBE_EDITOR="nvim"

export platusers="duboisf,marcantoine-bibeau,lavoiedn,jagdeepgithub,Masterdo,alexgervais,joanroch"

open_pull_request() {
    if [ ! -z $1 ] && [ $1 == 'all' ]; then
        prusers="-r $platusers"
    else
        prusers=""
    fi
    hub pull-request --copy $prusers
}

kube_templator_validate() {

    if [ ! -z $1 ] && [ $1 == 'local' ]; then
        templatorImg="ktvalidate:local"
    else
        templatorImg="docker.appdirect.tools/kube-templator/validate:latest"
    fi

    if [ ! -z $2 ]; then
        logLevel="$2"
    else
        logLevel="ERROR"
    fi

    docker run --rm -v $(pwd):/tmp -v "$HOME/.config/hub":/app/hub -e LOG_LEVEL=$logLevel $templatorImg
    rc=$?

    if [[ $rc != 0 ]]; then 
        echo "Execution error!"
    else
        echo "Success!"
    fi
}

alias ktvalidate="kube_templator_validate"
alias openpr="open_pull_request"
alias vpnstart="sudo openconnect -b --authgroup=Duo --user=leo.almeida iceman.appdirect.com"
alias vpnstartbatman="sudo openconnect -b --authgroup=Duo --user=leo.almeida batman.appdirect.com"
alias vpnstop="sudo pkill -SIGINT openconnect"
alias buildad="mvn clean install -pl '!appdirect' -Dmaven.test.skip=true -DskipTests=true"

PATH="$HOME/dev/src/platform/platform-army-knife/kubernetes/kops:$PATH"
