#!/bin/bash

abort() {
  printf "%s\n" "$@"
  return 1
}

if ! command -v gh >/dev/null; then
    abort "Command 'gh' not found. Please install github CLI and authenticate."
fi

export KUBE_EDITOR="nvim"
export REVIEWERS=""
export GOPRIVATE=github.intuit.com
export GITHUB_INTUIT_TOKEN=$(gh auth token -h github.intuit.com)

# add argocd dist in path
[ -d $HOME/dev/go/src/github.com/argoproj/argo-cd/dist ] && export PATH="${HOME}/dev/go/src/github.com/argoproj/argo-cd/dist:${PATH}"

openpr() {
    main=$(git remote show origin | awk '/HEAD branch/ {print $NF}')
    cmd="/usr/local/bin/hub pull-request --base $main --copy"
    if [ -n "$1" ] && [ "$1" = "all" ]; then
        cmd="$cmd -r $REVIEWERS"
    fi
    eval $cmd
}

decode() {
    echo -n "$1" | base64 -D | pbcopy
}

alias it="cd $HOME/dev/git/intuit"
